# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Marcio Oliveira
# Description of the Site
description: Marcio's virtual space
# URL of Image of the Site
site-image: /mfsoliveira.github.io/assets/images/meta.jpg

# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://github.com/mfsoliveira/mfsoliveira.github.io/raw/master/assets/images/background.JPG?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
#https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: marciofsoliveira@gmail.com
twitter_username: oliveira_mfs
linkedin_username: mfsoliveira
xing_username: Marcio_Oliveira4
github_username:  mfsoliveira


# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: mfsoliveira

# Name of the Author
author-name: Marcio Oliveira
# URL for the Image of the Author
author-image: assets\images\author.png
# 60 Words About the Author
author-about: I am a Software Developer crossing multiple fields, from Bioinformatics to Embedded Systems. I spend some time on R&D of tools for Hardware and Software co-development, such as estimation and design space exploration using the Model-Driven Development approach, which was the theme of my Ph.d.. But I also developed tools for simulation and verification at that time. Now I am at itemis AG, which is a consulting company. There I can work on quite different topics, such as Software Product-Line Engineering Tools or support the definition of Software Development process for Automotive Companies. Now I am learning Web Development, which I had my first experience long, long time ago. I believe we can write good software to support people in our daily activities, by building up bricks of solutions that sustain the bridge used by people to reach their next goal. That includes software to make software, because many projects are still drifting in their way to success.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
